---
name: "Slack Notifications"
guid: "94fb77c3-55ad-4c50-bf4e-4e5497467b79"
version: "5.0.0.0"
targetAbi: "10.5.0.0"
overview: "Get notifications via Slack"
description: >
  Get notifications via Slack.
category: "Notifications"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.Slack.dll"
changelog: >
  changelog
