---
name: "jellyfin-plugin-slack"
guid: "94fb77c3-55ad-4c50-bf4e-4e5497467b79"
version: "4"
jellyfin_version: "10.3.7"
nicename: "Slack Notifications"
description: "Get notifications via Slack"
overview: >
  Get notifications via Slack.
category: "Notifications"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.Slack.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "netstandard2.0"
